import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-4/5 m-auto bg-white mt-[-42px] rounded-tl-[1.875rem] min-h-[21.5rem] p-6 md:p-14 flex flex-wrap-reverse justify-around '>
        <div className='w-[35.75rem] max-h-80'>
          <h2 className='font-bold text-[#232323] text-2xl'>New Apex Legends Weapon Revealed, Havoc Arrives Today</h2>
          <p>New Apex Legends Weapon Revealed, Havoc Arrives Today</p>
        </div>
        <div className='w-[35.625rem] max-h-80'>
          <img className='w-full h-full object-cover rounded' src="" alt="Thumbnail" />
        </div>
      </div>
    </div>
  )
}

Home.getLayout = function getLayout(page){
  return <Layout title="News">{page}</Layout>
}
